---
#- name: Install MariaDB database from the repos
#  dnf:
#    name: mariadb-server
#    state: present

- name: Create scripts directory
  file:
    path: /home/sigstore/scripts
    state: directory

- name: Copy MariaDB / MySQL preparation script
  copy:
    src: "{{ item }}"
    dest: /home/sigstore/scripts/
  loop:
    - createdb.sh
    - storage.sql

- name: Run MariaDB / MySQL database and user preparation script
  command: sh createdb.sh
  args:
    chdir: /home/sigstore/scripts/
